import Header from '@/components/header';
import LoginForm from '@/components/login';
import Head from 'next/head';
import React from 'react';

export default function Login() {
  return (
    <>
      <Head>
        <title>Mosh NFT - Account Login</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Header />
      <LoginForm />
    </>
  );
}
