import Footer from '@/components/footer';
import Header from '@/components/header';
import LeadBoard from '@/components/leadboard';
import Head from 'next/head';

export default function LeadBoardPage() {
  return (
    <>
      <Head>
        <title>Mosh NFT - Lead Board</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Header />
      <LeadBoard />
      <Footer />
    </>
  );
}
