import NeverMissCTA from '@/components/NeverMissCTA';
import PublicProfile from '@/components/PublicProfile';
import Footer from '@/components/footer';
import Header from '@/components/header';
import Head from 'next/head';
import React from 'react';

const ProfilePublicPage = () => {
  return (
    <>
      <Head>
        <title>Mosh NFT - Profile</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Header />
      <PublicProfile />
      <div className='mt-20'></div>
      <NeverMissCTA />
      <Footer />
    </>
  );
};

export default ProfilePublicPage;
