import CallToAction from '@/components/callToAction';
import Footer from '@/components/footer';
import Header from '@/components/header';
import TrackData from '@/components/trackData';
import TrackOverview from '@/components/trackOverview';
import TrackPack from '@/components/trackPack';
import Head from 'next/head';
// import { Inter } from '@next/font/google';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {

  return (
    <>
      <Head>
        <title>Mosh NFT Marketplace</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <main className='min-h-screen overflow-hidden'>
        <Header />
        <TrackPack />
        <TrackData />
        <TrackOverview />
        <CallToAction />
        <Footer />
      </main>
    </>
  );
}
