import React from 'react';
import CallToAction from '@/components/callToAction';
import Footer from '@/components/footer';
import Header from '@/components/header';
import TrackData from '@/components/trackData';
import TrackOverview from '@/components/trackOverview';
import TrackPack from '@/components/trackPack';
import Head from 'next/head';

export default function Home() {

  return (
    <React.Fragment>
      <Head>
        <title>Mosh NFT Marketplace</title>
        <meta name='description' content='Generated by create next app' />
        <meta name="project description" content="Song NFT marketplace based on ethereum blockchain" />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <main className='min-h-screen overflow-hidden'>
        <Header />
        <TrackPack />
        <TrackData />
        <TrackOverview />
        <CallToAction />
        <Footer />
      </main>
    </React.Fragment>
  );
}
