import Footer from '@/components/footer';
import Header from '@/components/header';
import Head from 'next/head';
import React from 'react';
import {useRouter} from 'next/router';
import { loadStripe } from '@stripe/stripe-js';
import { Elements } from '@stripe/react-stripe-js';
import { UserContext } from '@/context/UserContext';
import CheckoutForm from "../../components/Checkout/CheckoutForm";

const stripePromise = loadStripe(process.env.STRIPE_PUBLISHABLE_KEY);

export default function CheckoutPage() {
    const router = useRouter();
    const {quentity} = router.query;
    const { state, createPaymentIntent } = React.useContext(UserContext);
    const [clientSecret, setClientSecret] = React.useState(null);

    React.useEffect(() => {
        const createPaymentIntentObject = () => {
          try { 
            createPaymentIntent(quentity);
          } catch(error) {
            console.log(error);
          }
        }
        createPaymentIntentObject();
    },[]);

    React.useEffect(() => {
        if(state.clientSecret !== null) {
          setClientSecret(state.clientSecret);
        }
    },[state.clientSecret]);

    return (
        <>
            <Head>
                <title>Mosh NFT - Checkout
                </title>
                <meta name='description' content='Generated by create next app'/>
                <meta name='viewport' content='width=device-width, initial-scale=1'/>
                <link rel='icon' href='/favicon.svg'/>
            </Head>
            <Header/>
            <div className=' ml-[20%] mr-[20%] bg-white p-10 mt-[200px] mb-[300px] rounded-3xl'>
               {clientSecret !== null && (
                <Elements stripe={stripePromise} options={{clientSecret}}>
                    <CheckoutForm  clientSecret={clientSecret}/>
                </Elements>
               )}
            </div>
            <Footer/>
        </>
    );
}
