import Footer from '@/components/footer';
import Header from '@/components/header';
import Head from 'next/head';
import React, { useContext } from 'react';
import {useRouter} from 'next/router';
import { loadStripe } from '@stripe/stripe-js';
import { Elements } from '@stripe/react-stripe-js';
import { UserContext } from '@/context/UserContext';
import CheckoutForm from "../../components/Checkout/CheckoutForm";
import Modal from '@/components/utils/elements/Modal';
import ErrorAlert from '@/components/utils/elements/ErrorAlert';
import Loading from '@/components/utils/elements/Loading';

const stripePromise = loadStripe(process.env.STRIPE_PUBLISHABLE_KEY);

export default function CheckoutPage() {
  const router = useRouter();
  const {quentity} = router.query;
  const {state} = useContext(UserContext);

  return (
    <>
      <Head>
        <title>Mosh NFT - Checkout
        </title>
        <meta name='description' content='Generated by create next app'/>
        <meta name='viewport' content='width=device-width, initial-scale=1'/>
        <link rel='icon' href='/favicon.svg'/>
      </Head>
      <Header/>
      <div className='md:ml-[30%] md:mr-[30%] sm:ml-[20%] sm:mr-[20%] bg-white p-10 mt-[200px] mb-[300px] rounded-3xl mr-[10%] ml-[10%]'>
        <Elements stripe={stripePromise}>
            <CheckoutForm  quentity={quentity}/>
        </Elements>
      </div>
      <Footer/>
      <ErrorAlert errorAlertVisible={state.error} message={state.errorMessage}/>  
      <Modal modalVisible={state.modal} modalTitle={state.modalTitle} modalContent={state.modalContent}/>   
      {state.loading && (<Loading/>)}   
    </>
  );
}
